### ISSUE TITLE
Awfultanker colour issues

### ISSUE THREAD

**Issue by Arkhorse** [Willster419/RelhaxModpackDatabase#32]
Awfultanker colour options have a patching issue

`"texture": "\"standard_blue64.dds\"",`

Slashes should not be added
"standard_green64.dds" is the actual requested patch

Current patch code:
`
<patchs>
  <patch>
    <type>json</type>
    <mode>edit</mode>
    <patchPath>app</patchPath> <file>\\res_mods\\versiondir\\scripts\\client\\gui\\mods\\at_servermarker\\AT_ServerMarker_config.json</file>
    <path>texture</path>
    <search>.*</search>
    <replace>standard_green64.dds</replace>
  </patch>
</patchs>
`
The result:

{
  `"texture": "\"standard_blue64.dds\"",`
  "textureScaleArcade": 0.65,
  "textureScaleSniper": 0.8,
  "markerScaleServer": 0.8,
  "markerScaleClient": 1.0,
  "hideClientMarkerReload": false,
  "preventTeamDamage": false,
  "showOnTop": false,
  "showUnsupported": true,
  "minimumSizeLimit": true
}

**Comment by Willster419** [comment]
not sure why the patcher would do this. when it detects a string type value for replace, it should place the value in raw. if you try to setup that patch manually in the designer, what does it do?

**Comment by Arkhorse** [comment]
Not this.... It works fine. Only after installing does it do this.

**Comment by Arkhorse** [comment]
I can no longer reproduce the issue. Re-enabling it and closing this.

**Comment by elektrosmoker** [comment]
some patches worked, but not all patches used the same format. i think this was a copy/paste issue.
FIXED 4 ALL COLORS
