### ISSUE TITLE
XVM Fonts Check (Pre-Builds)

### ISSUE THREAD

**Issue by Arkhorse** [Willster419/RelhaxModpackDatabase#36]
Fonts check for XVM

**Comment by Arkhorse** [comment]
d87e4fb0380ca1cca372509c5f8956714489d236

**Comment by Arkhorse** [comment]
06fcfcc28dd894420a9f6f7b62dfb9df0c1fa0ff

**Comment by Willster419** [comment]
Process is as follows:

- Manually uninstall fonts from windows that are in the modpack dependencies
- Make a selection file in `XVM config builder` that selects to enable (not adding new) components from the prebuild configuration. That way everything should be shown to verify if anything is missing.
- Select the prebuild to test and install
- Load a training room and inspect
- Check the python log for missing font errors

**Comment by Willster419** [comment]
Checked Default and Solo, no extra fonts needed

**Comment by Arkhorse** [comment]
[python.log](https://github.com/Willster419/RelhaxModpackDatabase/files/3343287/python.log)
Re: https://github.com/Willster419/RelhaxModpackDatabase/commit/b85e8a37121efb4bf424fe7c564076f6fbb10319

**Comment by Willster419** [comment]
quickeybaby xvm prebuilt does not use any custom fonts

**Comment by Arkhorse** [comment]
Dirty does not use any fonts

**Comment by Willster419** [comment]
oldskool is fine, no custom fonts

**Comment by Arkhorse** [comment]
Testing for Electrosmoker 
[python.log](https://github.com/Willster419/RelhaxModpackDatabase/files/3343308/python.log)

**Comment by Willster419** [comment]
NDO config does not need any custom fonts other then his font

**Comment by Arkhorse** [comment]
The Illusion's prebuilt does not fonts

**Comment by Arkhorse** [comment]
Willster's prebuild does not use fonts

**Comment by Willster419** [comment]
Jimbos does not use any custom fonts

**Comment by Willster419** [comment]
Heliomat does not load, there's issues with the boosters.py file @elektrosmoker

**Comment by Willster419** [comment]
Elkanos config does not use any custom fonts

**Comment by Arkhorse** [comment]
OMC uses "Inconsolata". @elektrosmoker the capture bar is broken here

**Comment by Arkhorse** [comment]
XVMPrebuiltConfigs_Aslain doesnt use fonts

**Comment by Willster419** [comment]
Druids does not use custom fonts

**Comment by Willster419** [comment]
Diclvit does not use custom fonts

**Comment by Willster419** [comment]
After testing, OMC, elektrosmoker, and 123 gauss configs work with the fonts installed.
