### ISSUE TITLE
XVM Fonts Check (Config Builder)

### ISSUE THREAD

**Issue by Arkhorse** [Willster419/RelhaxModpackDatabase#37]
This is for the Config Builder

**Comment by Willster419** [comment]
The package `XVMConfigBuilder_BattleInterface_HPpools_MIAPAK` uses the font `KAPb14 v1`, `Gunplay`, `Calligraph810 BT`. So far the only other packages that look to use custom fonts (in xvm) are debug panels

**Comment by Willster419** [comment]
After checking the other xvm config builder options, nothing else needed custom fonts.
