### ISSUE TITLE
[BUG] XVM not loading crew properly

### ISSUE THREAD

**Issue by Willster419** [Willster419/RelhaxModpackDatabase#45]
This issue is opened on behalf of `roadrunner142` from the relhax forums:
https://forums.relhaxmodpack.com/index.php?topic=103.new#new

**Describe the bug**
See picture. It's not showing his crew correctly.

**To Reproduce**
I have not attempted to reproduce yet.

**Expected behavior**
It should display all crew properly

**Screenshots**
![shot_021](https://user-images.githubusercontent.com/2482828/71548519-72afdc00-297d-11ea-9613-913f82ecb05f.jpg)

**Desktop (please complete the following information):**
 - OS: Windows 10

**Additional context**

**Logs** 

[pmod.log](https://github.com/Willster419/RelhaxModpackDatabase/files/4007357/pmod.log)
[python.log](https://github.com/Willster419/RelhaxModpackDatabase/files/4007358/python.log)
[RelHaxLog.txt](https://github.com/Willster419/RelhaxModpackDatabase/files/4007359/RelHaxLog.txt)

[xvm.log](https://github.com/Willster419/RelhaxModpackDatabase/files/4007360/xvm.log)

[RelHaxSettings.xml.txt](https://github.com/Willster419/RelhaxModpackDatabase/files/4007362/RelHaxSettings.xml.txt)
[lastInstalledConfig.xml.txt](https://github.com/Willster419/RelhaxModpackDatabase/files/4007363/lastInstalledConfig.xml.txt)

**Comment by Arkhorse** [comment]
Pretty sure this is a font issue

**Comment by Arkhorse** [comment]
This is the error... I think:

`2019-12-28 11:29:20: [L:024] TypeError: Error #1009: Cannot access a property or method of a null object reference.
	at com.xfw.infrastructure::XfwViewBase/onBeforePopulate()
	at com.xfw::XfwUtils/safeCall()
	at com.xfw.infrastructure::XfwViewBase/onBeforePopulatePrivate()
	at net.wg.infrastructure.base::BaseDAAPIComponent/as_populate()
	at net.wg.infrastructure.base.meta.impl::LoaderManagerMeta/viewLoadedS()
	at net.wg.infrastructure.managers.impl::LoaderManager/onSWFLoaded()`

**Comment by elektrosmoker** [comment]
![image](https://user-images.githubusercontent.com/40739360/71549203-bcb6b300-29b9-11ea-98e4-17c9e971ff69.png)
cannot replicate this one.

only thing i found in my logs is an error with auxilium. 
only this line:
`2019-12-28 21:30:10.335: WARNING: [Auxilium] An error occurred while reading the mod data from the file: res_mods/configs/BBMods/Auxilium.dat`

**Comment by Willster419** [comment]
hmm. I know auxilium works with crews as well. I'll take a look.

**Comment by Willster419** [comment]
I ran the V1 installer (gross) with his settings and selection file. No errors from the log file.
Launched the game, and it did have to reload once. I know some mods do this. @elektrosmoker @Arkhorse , did that happen to you as well?

I also was unable to replicate the issue, my client loaded in fine (the second time) and all crew members displayed as they should.
![shot_105](https://user-images.githubusercontent.com/2482828/71549503-b4944e80-298c-11ea-8188-95a8cfb35399.jpg)

@Arkhorse , I tried installing with not installing his fonts, and the issue didn't occur. So we can rule that out.

It's definitely an XVM issue. I would agree with @elektrosmoker , a cache clear first and see if the problem goes away.

**Comment by elektrosmoker** [comment]
> Launched the game, and it did have to reload once.
yes, it loaded twice.

even if i only use xvm it always loads twice for me. i think i never saw it loading into the game only once, not that i´ve noticed that...
which mods are guilty for loading twice? 
wotmods (mods), script mods (res_mods) or graphical mods (only images)?

**Comment by Willster419** [comment]
the only ones i remember (besides certain xvm configurations) are goofy's hangman and some audio bank management mod. We don't use the ladder.

I've told the user to try using Relhax V2 and clear cache. We'll see if that helps.

**Comment by Willster419** [comment]
Update:
I found someone else from the modpack email, `nuclearguy931`, with the exact same issue. Here's his Info:

> After downloading/updating the newest updates, I go and update from the XVM website. When I start up the game it does not indicate that I am running the latest version of XVM. The game loading screen shows the pictures the RelHax has added.

> Once in the garage, none of the selection I have checked off in the mod pack are working, gold, bond and free XP locker, the crew is not displayed, only a commander that doesn’t change on display no matter what tank I have displayed. When I try to return the crew of the vehicle to the tank it shows that the crew is already there.

> In the screenshots I have attached, it’s my American tank commander being displayed even though it’s a Swedish tank in the garage.

![shot_209](https://user-images.githubusercontent.com/2482828/71559743-f7f3c900-2a2f-11ea-9728-2bbb09389769.jpg)
![shot_210](https://user-images.githubusercontent.com/2482828/71559744-f7f3c900-2a2f-11ea-8d44-2101b776c599.jpg)

**Comment by Willster419** [comment]
[RelhaxModpackLogs_2019-12-28_18-01-56.zip](https://github.com/Willster419/RelhaxModpackDatabase/files/4008271/RelhaxModpackLogs_2019-12-28_18-01-56.zip)

**Comment by Willster419** [comment]
also got more info from `roaderrunner142`

> It is definitely XVM as i did an install without XVM checked and everything is fine. I also did an install with just XVM from the XVM site and had the same loss of crew in tanks. I am currently loaded with all the mods except XVM i've used for 6 years and no problems.

So it's 100% at the fault of something with XVM. What I found is that the `clear cache` option from the modpack was written to match inno setup code back in 2017 from grumpel. it clears all cache, but backs up the game settings `prefrences.xml`, and the xvm and pmod folders.

Upon looking at the pmod and xvm folders, it looks like they both contain a mix of cache and actual data. I'm going to suggest the following to both users:

1. Delete the xvm folder in `C:\Users\{username}\AppData\Roaming\Wargaming.net\WorldOfTanks\xvm`

2. re-sign into the xvm website and remove all account tokens: https://i.imgur.com/Fpnioxa.png

**Comment by Willster419** [comment]
replying again because a user had a similar problem, and just posted on the forums:
http://forum.worldoftanks.eu/index.php?/topic/623269-1702-the-relhax-modpack-omc-20-fastest-mods-installer-with-previews/page__st__1000__pid__17488580#entry17488580

So try removing the "mods" and "res_mods" folders (if they exist) in the win32 and win64 folders, that should do it!

**Comment by Willster419** [comment]
Just confirmed from `roadrunner142` that the issue has been solved.

> Followed instructions from other user and all problems gone now. Thank you for all your assistance with this matter.

END SOLUTION: delete the "mods" and "res_mods" folders in the win32 and win64 folders. XVM seems to pick them up by mistake and try to use them.
