### ISSUE TITLE
1.10.0.4 todo

### ISSUE THREAD

**Issue by Willster419** [Willster419/RelhaxModpackDatabase#52]
### Use the sheet for packages known to need updates
 - https://docs.google.com/document/d/1RHmEw4WI9NWrhVaYn5yBF4hzJeBRDEvMDxNVC4JjnZM/edit

### XVM
- Regular update of xvm package itself
- The configurations did not significantly change
- Update PY / XC scripts
- Update hawgs (or at least check)

### Crosshairs
- Nothing seems to have changed
- Check a crosshair, if it works we good
- Check gun constraints

### Contour Icons
- Added new premium tank
- Check for updates but can skip for publish

### Ingame Misc / Info/ Aim Damage log panel
- Regular update checks
- Same skips as below

### Garage Mods
- Check gui/script
- Can skip image
- Can skip patches

### Garage Graphics
- Regular update checks
- Can skip picture packages

### Statistics
- Regular update checks

### Sound mods
- Test them
- Don't bother updating because they are going to release a patch later

### 6th sense
- Update champi
- Test dependency

### Tank Skins misc
- General check for updates

### Tank skins/remodels
- No big change from patch
- TODO:
  -  SWEDEN
  -  USA
  -  UK
  -  USSR

**Comment by Arkhorse** [comment]
Since we are now on `1.11.0.0`, I will close this issue.
