### ISSUE TITLE
Potentially removing XML based skins/remodels from the modpack

### ISSUE THREAD

**Issue by Arkhorse** [Willster419/RelhaxModpackDatabase#54]
Aslain has stated he may remove all `XML` based skins/remodels from his modpack [Link to msg on his Discord](https://discord.com/channels/305615825413603338/728150295527555072/786139902810128384).

I am tempted to do the same. This would make the `TankSkinsRemodels` category less volatile when WG changes the XML's of tanks, but would remove popular mods from our modpack.

So, I am posting this here to get some public feedback on this issue. What do you think? Should I do it?

PS: Yes, I know we are getting Automation. When that system is finished, I may reverse this action as it would no longer matter in the same way (would still need to wait for the actual updates though)

**Comment by Willster419** [comment]
I'd argue to hide them. That way as far as users are concerned, we removed them to follow aslain. If automation proves to handle these, then we can put them back.

**Comment by Arkhorse** [comment]
Ok, that makes sense. Ill see about doing that today/tomorrow

**Comment by Arkhorse** [comment]
Thats every package I know of that has an xml in it

**Comment by Arkhorse** [comment]
Here is something I just thought of:

For XML based mods, using the patcher, patch the base game xml. This would require extracting the file from `\scripts\item_defs\vehicles\`, and decoding them. Since most of the xml changes are position changes, this would mean that these mods wont break as often. 

This is with the automation thingy.

**Comment by Willster419** [comment]
> Here is something I just thought of:
> 
> For XML based mods, using the patcher, patch the base game xml. This would require extracting the file from `\scripts\item_defs\vehicles\`, and decoding them. Since most of the xml changes are position changes, this would mean that these mods wont break as often.
> 
> This is with the automation thingy.

The skins were removed, and with automation in its current state, if it were brought back, you could have it auto-update packages. Additionally, we could write it so that it would disable packages if the wgmods text doesn't say it supports the current client.
